// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhsswtixtrurxpsrduus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoc3N3dGl4dHJ1cnhwc3JkdXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODk1NzYsImV4cCI6MjA2MDU2NTU3Nn0.apQbIt-eN9U6yJeL7zPVyodecxbDFUymFtFVkQzOmsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);